name: verfify-platform
run-name: Verify IaC
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  infracost-analysis:
    name: Cloud cost analysis
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-southeast-2
    #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    #     role-duration-seconds: 1200
    - name: Checkout Source Code
      uses: actions/checkout@v3
    # # https://github.com/infracost/actions/
    # - name: Setup Infracost
    #   uses: infracost/actions/setup@v2
    # - name: Configure Infracost
    #   run: |
    #     infracost configure set pricing_api_endpoint http://202.138.30.211:60001
    #     infracost configure set api_key 27D7AFPwHEu5nhmy27aBRbFrwNfGzhe0
    # - name: Checkout base branch
    #   if: ${{ github.event_name == 'pull_request' }}
    #   uses: actions/checkout@v3
    #   with:
    #     ref: '${{ github.event.pull_request.base.ref }}'    
    # - name: Generate Infracost cost estimate baseline
    #   run: |
    #     infracost breakdown --path=./terraform \
    #                         --format=json \
    #                         --out-file=/tmp/infracost-base.json    
    # - name: Checkout PR branch
    #   uses: actions/checkout@v3
    # - name: Generate Infracost diff
    #   run: |
    #     infracost diff --path=./terraform \
    #                     --format=json \
    #                     --compare-to=/tmp/infracost-base.json \
    #                     --out-file=/tmp/infracost.json
    # - name: Post Infracost comment
    #   run: |
    #       infracost comment github --path=/tmp/infracost.json \
    #                                 --repo=$GITHUB_REPOSITORY \
    #                                 --github-token=${{github.token}} \
    #                                 --pull-request=${{github.event.pull_request.number}} \
    #                                 --behavior=update
    # https://github.com/marketplace/actions/trufflehog-oss
    # - name: TruffleHog Scan
    #   uses: trufflesecurity/trufflehog@main
    #   with:
    #     path: ./
    #     base: ${{ github.event.repository.default_branch }}
    #     head: HEAD
    - name: Pull Conftest policy
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install conftest
        conftest pull git::https://github.com/rallyhealth/conftest-policy-packs.git//policies
        conftest test terraform/main.tf --output=github



